version: "3"

services:
  lpz-solver:
    build: .
    container_name: lpz-solver
    ports:
      - "$PORT:$PORT"
    secrets:
      - score-solver_config.yaml
#     networks:
#       - networkName

secrets:
  score-solver_config.yaml:
    file: ../.secrets/score-solver_config.yaml
# networks:
#   lpz-db:
#     name: lpz-db_lpz-db